// Mocks generated by Mockito 5.4.0 from annotations
// in fun_with_pdf/test/view_pdf/domain/usecases/get_data_from_file_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fun_with_pdf/view_pdf/domain/entities.dart' as _i2;
import 'package:fun_with_pdf/view_pdf/domain/repository/pdf_data_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfBytes_0 extends _i1.SmartFake implements _i2.PdfBytes {
  _FakePdfBytes_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PdfDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockPdfDataRepository extends _i1.Mock implements _i3.PdfDataRepository {
  @override
  _i4.Future<_i2.PdfBytes> getDataFromFile() => (super.noSuchMethod(
        Invocation.method(
          #getDataFromFile,
          [],
        ),
        returnValue: _i4.Future<_i2.PdfBytes>.value(_FakePdfBytes_0(
          this,
          Invocation.method(
            #getDataFromFile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PdfBytes>.value(_FakePdfBytes_0(
          this,
          Invocation.method(
            #getDataFromFile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PdfBytes>);
}
