// Mocks generated by Mockito 5.4.0 from annotations
// in fun_with_pdf/test/src/presentation/view_pdf/pdf_view_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:fun_with_pdf/core/fialure.dart' as _i6;
import 'package:fun_with_pdf/src/domain/entities.dart' as _i7;
import 'package:fun_with_pdf/src/domain/view_pdf/repository/pdf_data_repository.dart'
    as _i2;
import 'package:fun_with_pdf/src/domain/view_pdf/usecases/get_data_from_file.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfDataRepository_0 extends _i1.SmartFake
    implements _i2.PdfDataRepository {
  _FakePdfDataRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataFromFile].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDataFromFile extends _i1.Mock implements _i4.DataFromFile {
  @override
  _i2.PdfDataRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePdfDataRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakePdfDataRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PdfDataRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.PdfBytes>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.PdfBytes>>.value(
            _FakeEither_1<_i6.Failure, _i7.PdfBytes>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.PdfBytes>>.value(
                _FakeEither_1<_i6.Failure, _i7.PdfBytes>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.PdfBytes>>);
}
